//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace AtApi.Model
{
   /// <summary>
   /// Class
   /// </summary>
   public partial class Class
   {
      partial void Init();

      /// <summary>
      /// Default constructor. Protected due to required properties, but present because EF needs it.
      /// </summary>
      protected Class()
      {
         Schedules = new System.Collections.Generic.HashSet<global::AtApi.Model.At.Schedule>();

         Init();
      }

      /// <summary>
      /// Replaces default constructor, since it's protected. Caller assumes responsibility for setting all required values before saving.
      /// </summary>
      public static Class CreateClassUnsafe()
      {
         return new Class();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="name">Name</param>
      /// <param name="description">Description</param>
      /// <param name="code">Code</param>
      /// <param name="subjectid">Subject</param>
      /// <param name="estimatednumberofstudents">Estimated Number of Students</param>
      /// <param name="teacherid">TeacherId</param>
      public Class(string name, string description, string code, int subjectid, int estimatednumberofstudents, int teacherid)
      {
         if (string.IsNullOrEmpty(name)) throw new ArgumentNullException(nameof(name));
         this.Name = name;

         if (string.IsNullOrEmpty(description)) throw new ArgumentNullException(nameof(description));
         this.Description = description;

         if (string.IsNullOrEmpty(code)) throw new ArgumentNullException(nameof(code));
         this.Code = code;

         this.SubjectId = subjectid;

         this.EstimatedNumberOfStudents = estimatednumberofstudents;

         this.TeacherId = teacherid;

         this.Schedules = new System.Collections.Generic.HashSet<global::AtApi.Model.At.Schedule>();

         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="name">Name</param>
      /// <param name="description">Description</param>
      /// <param name="code">Code</param>
      /// <param name="subjectid">Subject</param>
      /// <param name="estimatednumberofstudents">Estimated Number of Students</param>
      /// <param name="teacherid">TeacherId</param>
      public static Class Create(string name, string description, string code, int subjectid, int estimatednumberofstudents, int teacherid)
      {
         return new Class(name, description, code, subjectid, estimatednumberofstudents, teacherid);
      }

      /*************************************************************************
       * Properties
       *************************************************************************/

      /// <summary>
      /// Identity, Required
      /// Id
      /// </summary>
      [Key]
      [Required]
      public int Id { get; protected set; }

      /// <summary>
      /// Required, Max length = 10000
      /// Name
      /// </summary>
      [Required]
      [MaxLength(10000)]
      [StringLength(10000)]
      public string Name { get; set; }

      /// <summary>
      /// Required, Max length = 10000
      /// Description
      /// </summary>
      [Required]
      [MaxLength(10000)]
      [StringLength(10000)]
      public string Description { get; set; }

      /// <summary>
      /// Required, Max length = 100
      /// Code
      /// </summary>
      [Required]
      [MaxLength(100)]
      [StringLength(100)]
      public string Code { get; set; }

      /// <summary>
      /// Required
      /// Subject
      /// </summary>
      [Required]
      public int SubjectId { get; set; }

      /// <summary>
      /// Required
      /// Estimated Number of Students
      /// </summary>
      [Required]
      public int EstimatedNumberOfStudents { get; set; }

      /// <summary>
      /// Required
      /// TeacherId
      /// </summary>
      [Required]
      public int TeacherId { get; set; }

      /*************************************************************************
       * Navigation properties
       *************************************************************************/

      /// <summary>
      /// Schedules
      /// </summary>
      public virtual ICollection<global::AtApi.Model.At.Schedule> Schedules { get; protected set; }

      /// <summary>
      /// Teacher
      /// </summary>
      /// <remarks>
      /// Teacher
      /// </remarks>
      public virtual global::AtApi.Model.Teacher Teacher { get; set; }

   }
}

