//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace AtApi.Model.At
{
   /// <summary>
   /// Enrollment
   /// </summary>
   public partial class Enrollment
   {
      partial void Init();

      /// <summary>
      /// Default constructor. Protected due to required properties, but present because EF needs it.
      /// </summary>
      protected Enrollment()
      {
         Init();
      }

      /// <summary>
      /// Replaces default constructor, since it's protected. Caller assumes responsibility for setting all required values before saving.
      /// </summary>
      public static Enrollment CreateEnrollmentUnsafe()
      {
         return new Enrollment();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="classid">Foreign key for Class.Enrollments &lt;--&gt; Enrollment.Class_. </param>
      /// <param name="studentid">Foreign key for Student.Enrollments &lt;--&gt; Enrollment.Student. </param>
      /// <param name="class_"></param>
      /// <param name="student"></param>
      public Enrollment(int classid, int studentid, global::AtApi.Model.At.Class class_, global::AtApi.Model.At.Student student)
      {
         this.ClassId = classid;

         this.StudentId = studentid;

         if (class_ == null) throw new ArgumentNullException(nameof(class_));
         this.Class_ = class_;

         if (student == null) throw new ArgumentNullException(nameof(student));
         this.Student = student;


         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="classid">Foreign key for Class.Enrollments &lt;--&gt; Enrollment.Class_. </param>
      /// <param name="studentid">Foreign key for Student.Enrollments &lt;--&gt; Enrollment.Student. </param>
      /// <param name="class_"></param>
      /// <param name="student"></param>
      public static Enrollment Create(int classid, int studentid, global::AtApi.Model.At.Class class_, global::AtApi.Model.At.Student student)
      {
         return new Enrollment(classid, studentid, class_, student);
      }

      /*************************************************************************
       * Properties
       *************************************************************************/

      /// <summary>
      /// Identity, Required
      /// Id
      /// </summary>
      [Key]
      [Required]
      public int Id { get; protected set; }

      /// <summary>
      /// Indexed, Required
      /// Foreign key for Class.Enrollments &lt;--&gt; Enrollment.Class_. 
      /// </summary>
      [Required]
      public int ClassId { get; set; }

      /// <summary>
      /// Indexed, Required
      /// Foreign key for Student.Enrollments &lt;--&gt; Enrollment.Student. 
      /// </summary>
      [Required]
      public int StudentId { get; set; }

      /*************************************************************************
       * Navigation properties
       *************************************************************************/

      /// <summary>
      /// Required
      /// </summary>
      public virtual global::AtApi.Model.At.Class Class_ { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      public virtual global::AtApi.Model.At.Student Student { get; set; }

   }
}

