//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace AtApi.Model.At
{
   /// <summary>
   /// Schedule
   /// </summary>
   public partial class Schedule
   {
      partial void Init();

      /// <summary>
      /// Default constructor. Protected due to required properties, but present because EF needs it.
      /// </summary>
      protected Schedule()
      {
         Classes = new System.Collections.Generic.List<global::AtApi.Model.At.Class>();

         Init();
      }

      /// <summary>
      /// Replaces default constructor, since it's protected. Caller assumes responsibility for setting all required values before saving.
      /// </summary>
      public static Schedule CreateScheduleUnsafe()
      {
         return new Schedule();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="name">Name</param>
      /// <param name="day">Day</param>
      /// <param name="time">Time</param>
      public Schedule(string name, global::AtApi.Model.At.ScheduleDays day, string time)
      {
         if (string.IsNullOrEmpty(name)) throw new ArgumentNullException(nameof(name));
         this.Name = name;

         this.Day = day;

         if (string.IsNullOrEmpty(time)) throw new ArgumentNullException(nameof(time));
         this.Time = time;

         this.Classes = new System.Collections.Generic.List<global::AtApi.Model.At.Class>();

         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="name">Name</param>
      /// <param name="day">Day</param>
      /// <param name="time">Time</param>
      public static Schedule Create(string name, global::AtApi.Model.At.ScheduleDays day, string time)
      {
         return new Schedule(name, day, time);
      }

      /*************************************************************************
       * Properties
       *************************************************************************/

      /// <summary>
      /// Identity, Indexed, Required
      /// Id
      /// </summary>
      [Key]
      [Required]
      public int Id { get; protected set; }

      /// <summary>
      /// Required
      /// Name
      /// </summary>
      [Required]
      public string Name { get; set; }

      /// <summary>
      /// Required
      /// Day
      /// </summary>
      [Required]
      public global::AtApi.Model.At.ScheduleDays Day { get; set; }

      /// <summary>
      /// Required, Max length = 100
      /// Time
      /// </summary>
      [Required]
      [MaxLength(100)]
      [StringLength(100)]
      public string Time { get; set; }

      /*************************************************************************
       * Navigation properties
       *************************************************************************/

      public virtual ICollection<global::AtApi.Model.At.Class> Classes { get; protected set; }

   }
}

