//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace AtApi.Model
{
   /// <summary>
   /// Schedule Days
   /// </summary>
   /// <remarks>
   /// Schedule Days
   /// </remarks>
   public enum ScheduleDays : Int32
   {
      /// <summary>
      /// Sunday
      /// </summary>
      [System.ComponentModel.DataAnnotations.Display(Name="Sunday")]
      Sunday = 1,
      /// <summary>
      /// Monday
      /// </summary>
      [System.ComponentModel.DataAnnotations.Display(Name="Monday")]
      Monday = 2,
      /// <summary>
      /// Tuesday
      /// </summary>
      /// <remarks>
      /// Tuesday
      /// </remarks>
      [System.ComponentModel.DataAnnotations.Display(Name="Tuesday")]
      Tuesday = 3,
      /// <summary>
      /// Wednesday
      /// </summary>
      [System.ComponentModel.DataAnnotations.Display(Name="Wednesday")]
      Wednesday = 4,
      /// <summary>
      /// Thursday
      /// </summary>
      [System.ComponentModel.DataAnnotations.Display(Name="Thursday")]
      Thursday = 5,
      /// <summary>
      /// Friday
      /// </summary>
      [System.ComponentModel.DataAnnotations.Display(Name="Friday")]
      Friday = 6,
      /// <summary>
      /// Saturday
      /// </summary>
      [System.ComponentModel.DataAnnotations.Display(Name="Saturday")]
      Saturday = 7,
      /// <summary>
      /// WeekDays
      /// </summary>
      [System.ComponentModel.DataAnnotations.Display(Name="WeekDays")]
      WeekDays = 8,
      /// <summary>
      /// Weekends
      /// </summary>
      [System.ComponentModel.DataAnnotations.Display(Name="Weekends")]
      Weekends = 9,
      /// <summary>
      /// EveryDay
      /// </summary>
      [System.ComponentModel.DataAnnotations.Display(Name="EveryDay")]
      EveryDay = 10,
      /// <summary>
      /// Monday, Wednesday, Friday
      /// </summary>
      [System.ComponentModel.DataAnnotations.Display(Name="MWF")]
      MWF = 11,
      /// <summary>
      /// Tuesday, Thursday
      /// </summary>
      [System.ComponentModel.DataAnnotations.Display(Name="TuTh")]
      TuTh = 12
   }
}
