name: .NET Core

on:
  push:
    branches: 
      - master
      - develop
      - release/*
  pull_request:
    branches: 
      - master
      - develop
      - release/*
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore "AtApi Solution\AtApi Solution.sln"
    - name: Build
      run: dotnet build "AtApi Solution\AtApi\AtApi.csproj" --configuration Release --no-restore
    - name: Test
      run: dotnet test "AtApi Solution\AtApi.UnitTests\AtApi.UnitTests.csproj" --no-restore --verbosity normal --collect:"XPlat Code Coverage"
      